### ISSUE TITLE
Finish Donation Page and Flow

### ISSUE THREAD

**Issue by mfuery** [mfuery/savesmb#44]
Done. Needs styling and test on prod.

**Comment by mfuery** [comment]
@localallieshelp John donations are ready to be tested on production! Real money should move!

**Comment by mfuery** [comment]
Verified by John, it really does work!

![Screen Shot 2021-03-18 at 1 14 57 AM](https://user-images.githubusercontent.com/78221/111593655-67fe8400-8787-11eb-85c3-bf99214be7e2.png)

Thanks

**Comment by localallieshelp** [comment]
Awesome, thanks!
