### ISSUE TITLE
Donation page should show Square's transaction fee and add that to the charged donation amount

### ISSUE THREAD

**Issue by mfuery** [mfuery/savesmb#55]

**Comment by mfuery** [comment]
It would help to have a UX design. I will implement the functionality but it may not look pretty :)

**Comment by localallieshelp** [comment]
Haha. Would you want me to tap Courtney or someone else to assist?

**Comment by mfuery** [comment]
Yeah, that would be great

**Comment by mfuery** [comment]
Ready for test on stage at:
https://605436f880e4d300079be5bb--localallies.netlify.app/en/donate?b=Thai%20Chaiyo

**Comment by localallieshelp** [comment]
Courtney is working on a design. Should be complete by last week of March or earlier.
